# Generated by Django 5.2.13 on 2026-05-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='縣市')),
            ],
            options={
                'verbose_name': '縣市',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('591_existing', '591非預售'), ('591_presale', '591預售'), ('history', '歷史交易')], db_index=True, max_length=30, verbose_name='資料來源')),
                ('import_batch_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='匯入批次key')),
                ('building_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='建物型態')),
                ('project_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='建案名稱')),
                ('area_ping', models.FloatField(blank=True, null=True, verbose_name='坪數')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='單價_萬元坪')),
                ('transfer_floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='移轉層次')),
                ('transfer_floor_clean', models.IntegerField(blank=True, null=True, verbose_name='移轉層次_清理後')),
                ('total_floors', models.FloatField(blank=True, null=True, verbose_name='總樓層數')),
                ('building_age', models.FloatField(blank=True, null=True, verbose_name='屋齡')),
                ('building_age_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='屋齡_temp')),
                ('is_presale', models.BooleanField(default=False, verbose_name='is_presale')),
                ('age_was_missing', models.BooleanField(default=False, verbose_name='age_was_missing')),
                ('deal_year', models.IntegerField(blank=True, null=True, verbose_name='成交年')),
                ('deal_month', models.IntegerField(blank=True, null=True, verbose_name='成交月')),
                ('months_since_deal', models.IntegerField(blank=True, null=True, verbose_name='交易距今月數')),
                ('time_index', models.FloatField(blank=True, null=True, verbose_name='time_index')),
                ('elevator', models.IntegerField(blank=True, null=True, verbose_name='電梯')),
                ('main_building_ping', models.FloatField(blank=True, null=True, verbose_name='主建物坪數')),
            ],
            options={
                'verbose_name': '房屋主資料',
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='鄉鎮市區')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city', verbose_name='縣市')),
            ],
            options={
                'verbose_name': '鄉鎮市區',
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='House591PresaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.FloatField(blank=True, db_index=True, null=True, verbose_name='hid')),
                ('building_type_temp', models.FloatField(blank=True, null=True, verbose_name='建物型態_temp')),
                ('area_temp', models.CharField(blank=True, max_length=100, null=True, verbose_name='坪數_temp')),
                ('price_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='價錢單位')),
                ('total_price_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='總價範圍')),
                ('unit_price_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='單價_萬元坪區間')),
                ('layout', models.CharField(blank=True, max_length=100, null=True, verbose_name='格局')),
                ('url', models.TextField(blank=True, null=True, verbose_name='網址')),
                ('has_management', models.FloatField(blank=True, null=True, verbose_name='有無管理組織')),
                ('land_transfer_area_m2', models.FloatField(blank=True, null=True, verbose_name='土地移轉總面積平方公尺')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='標題')),
                ('handover_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='交屋時間')),
                ('total_floor_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='總樓層')),
                ('area_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='坪數區間')),
                ('avg_unit_price', models.FloatField(blank=True, null=True, verbose_name='單價_萬元坪_均價')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.property', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '591預售明細',
                'db_table': 'house_591_presale_detail',
            },
        ),
        migrations.CreateModel(
            name='House591ExistingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='post_id')),
                ('kind_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind_name')),
                ('type_value', models.FloatField(blank=True, null=True, verbose_name='類型')),
                ('car_shed', models.FloatField(blank=True, null=True, verbose_name='車棚')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('total_price', models.BigIntegerField(blank=True, null=True, verbose_name='總價')),
                ('unit_price_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='unit_price')),
                ('layout', models.CharField(blank=True, max_length=100, null=True, verbose_name='layout')),
                ('floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='floor')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='photo')),
                ('community', models.CharField(blank=True, max_length=150, null=True, verbose_name='community')),
                ('views', models.IntegerField(default=0, verbose_name='瀏覽次數')),
                ('url', models.TextField(blank=True, null=True, verbose_name='url')),
                ('use_google', models.IntegerField(default=0, verbose_name='use_google')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.property', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '591非預售明細',
                'db_table': 'house_591_existing_detail',
            },
        ),
        migrations.CreateModel(
            name='HistoryTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_transfer_area_m2', models.FloatField(blank=True, null=True, verbose_name='土地移轉總面積平方公尺')),
                ('building_transfer_area_m2', models.FloatField(blank=True, null=True, verbose_name='建物移轉總面積平方公尺')),
                ('has_management', models.IntegerField(blank=True, null=True, verbose_name='有無管理組織')),
                ('transaction_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易標的')),
                ('main_building_area', models.FloatField(blank=True, null=True, verbose_name='主建物面積')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.property', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '歷史交易明細',
                'db_table': 'history_transaction_detail',
            },
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_district', models.CharField(blank=True, max_length=50, null=True, verbose_name='完整行政區')),
                ('full_address', models.CharField(db_index=True, max_length=500, verbose_name='土地位置建物門牌')),
                ('clean_geo', models.TextField(blank=True, null=True, verbose_name='乾淨地理位置')),
                ('clean_address', models.TextField(blank=True, null=True, verbose_name='乾淨地址')),
                ('unique_geo', models.TextField(blank=True, null=True, verbose_name='唯一地理位置')),
                ('remove_no', models.CharField(blank=True, max_length=150, null=True, verbose_name='去號')),
                ('remove_lane', models.CharField(blank=True, max_length=150, null=True, verbose_name='去弄')),
                ('remove_alley', models.CharField(blank=True, max_length=150, null=True, verbose_name='去巷')),
                ('final_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='最後地址')),
                ('address_used', models.FloatField(blank=True, null=True, verbose_name='用哪個地址')),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True, verbose_name='經度')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.district', verbose_name='鄉鎮市區')),
            ],
            options={
                'verbose_name': '房屋地址位置',
                'db_table': 'property_location',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.propertylocation', verbose_name='地理位置'),
        ),
        migrations.CreateModel(
            name='PropertyPOIFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenience_300m', models.IntegerField(default=0, verbose_name='poi_convenience_count_300m')),
                ('convenience_500m', models.IntegerField(default=0, verbose_name='poi_convenience_count_500m')),
                ('bank_500m', models.IntegerField(default=0, verbose_name='poi_bank_count_500m')),
                ('food_300m', models.IntegerField(default=0, verbose_name='poi_food_count_300m')),
                ('food_500m', models.IntegerField(default=0, verbose_name='poi_food_count_500m')),
                ('medical_500m', models.IntegerField(default=0, verbose_name='poi_medical_count_500m')),
                ('parking_500m', models.IntegerField(default=0, verbose_name='poi_parking_count_500m')),
                ('distance_to_worship', models.FloatField(blank=True, null=True, verbose_name='distance_to_nearest_worship_m')),
                ('distance_to_thsr', models.FloatField(blank=True, null=True, verbose_name='distance_to_thsr_m')),
                ('distance_to_tra', models.FloatField(blank=True, null=True, verbose_name='distance_to_tra_m')),
                ('distance_to_mrt', models.FloatField(blank=True, null=True, verbose_name='distance_to_mrt_m')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.property', verbose_name='房屋')),
            ],
            options={
                'verbose_name': 'POI 特徵',
                'db_table': 'property_poi_feature',
            },
        ),
        migrations.CreateModel(
            name='PropertyPredictionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_last_month_price', models.FloatField(blank=True, null=True, verbose_name='area_last_month_price')),
                ('total_encoded', models.FloatField(blank=True, null=True, verbose_name='總_編碼')),
                ('area_age_interaction', models.FloatField(blank=True, null=True, verbose_name='坪數_屋齡_交互')),
                ('prediction', models.FloatField(blank=True, null=True, verbose_name='預測')),
                ('prediction_avg', models.FloatField(blank=True, null=True, verbose_name='預測_均價')),
                ('prediction_min', models.FloatField(blank=True, null=True, verbose_name='預測結果_最小值')),
                ('prediction_max', models.FloatField(blank=True, null=True, verbose_name='預測結果_最大值')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.property', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '預測特徵',
                'db_table': 'property_prediction_feature',
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique_city_district'),
        ),
        migrations.AddIndex(
            model_name='propertylocation',
            index=models.Index(fields=['latitude', 'longitude'], name='property_lo_latitud_d48a94_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylocation',
            index=models.Index(fields=['full_address'], name='property_lo_full_ad_0c42e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertylocation',
            constraint=models.UniqueConstraint(fields=('district', 'full_address', 'latitude', 'longitude'), name='unique_property_location'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['source_type'], name='property_source__158820_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['deal_year', 'deal_month'], name='property_deal_ye_98ecb5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['building_type'], name='property_buildin_c35e87_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['area_ping'], name='property_area_pi_3ecfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['unit_price'], name='property_unit_pr_97bccc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['building_age'], name='property_buildin_f97ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['import_batch_key'], name='property_import__3b2871_idx'),
        ),
    ]
