# Generated by Django 5.2.13 on 2026-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_propertypredictionfeature_prediction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='filter_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='篩選刪除原因'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_training_valid',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否為有效訓練資料'),
        ),
    ]
