# Generated by Django 5.2.13 on 2026-06-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_property_filter_reason_property_is_training_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='source_type',
            field=models.CharField(choices=[('591_existing', '591非預售'), ('591_presale', '591預售'), ('history', '歷史交易'), ('sinyi', '信義房屋')], db_index=True, max_length=30, verbose_name='資料來源'),
        ),
        migrations.CreateModel(
            name='SinyiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100, unique=True, verbose_name='houseNo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('image', models.TextField(blank=True, null=True, verbose_name='image')),
                ('large_image', models.TextField(blank=True, null=True, verbose_name='largeImage')),
                ('image_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='imageTag')),
                ('comm_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='commId')),
                ('comm_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='commName')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='discount')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('age_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='age')),
                ('houselandtype', models.CharField(blank=True, max_length=100, null=True, verbose_name='houselandtype')),
                ('houselandtype_show', models.CharField(blank=True, max_length=100, null=True, verbose_name='houselandtypeShow')),
                ('price_first', models.BigIntegerField(blank=True, null=True, verbose_name='priceFirst')),
                ('area_land', models.FloatField(blank=True, null=True, verbose_name='地坪')),
                ('is_has_balcony', models.IntegerField(blank=True, null=True, verbose_name='陽台')),
                ('layout', models.CharField(blank=True, max_length=100, null=True, verbose_name='格局')),
                ('is_parking', models.BooleanField(default=False, verbose_name='停車場')),
                ('parking', models.CharField(blank=True, max_length=255, null=True, verbose_name='parking')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='tags')),
                ('three_months_clicks', models.IntegerField(db_index=True, default=0, verbose_name='點擊率')),
                ('is_off', models.BooleanField(default=False, verbose_name='isOff')),
                ('is_similar', models.BooleanField(default=False, verbose_name='isSimilar')),
                ('share_url', models.TextField(blank=True, null=True, verbose_name='shareURL')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('kind', models.IntegerField(blank=True, null=True, verbose_name='kind')),
                ('object_type', models.IntegerField(blank=True, null=True, verbose_name='objectType')),
                ('is_3dvr', models.BooleanField(default=False, verbose_name='3DVR')),
                ('is_3dvr2', models.BooleanField(default=False, verbose_name='Is3Dvr')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='zipCode')),
                ('group_company', models.FloatField(blank=True, null=True, verbose_name='groupCompany')),
                ('add_layout', models.CharField(blank=True, max_length=255, null=True, verbose_name='addLayout')),
                ('total_layout', models.CharField(blank=True, max_length=255, null=True, verbose_name='totalLayout')),
                ('is_has_video', models.BooleanField(default=False, verbose_name='isHasVideo')),
                ('is_has_view', models.BooleanField(default=False, verbose_name='isHasView')),
                ('city_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='city_name')),
                ('city_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='city_code')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='page')),
                ('source_url', models.TextField(blank=True, null=True, verbose_name='source_url')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.property', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '信義房屋明細',
                'db_table': 'sinyi_detail',
                'indexes': [models.Index(fields=['house_no'], name='sinyi_detai_house_n_1d266c_idx'), models.Index(fields=['three_months_clicks'], name='sinyi_detai_three_m_bde88a_idx'), models.Index(fields=['discount'], name='sinyi_detai_discoun_d3389a_idx'), models.Index(fields=['price_first'], name='sinyi_detai_price_f_e4566e_idx')],
            },
        ),
    ]
