# Generated by Django 5.2.13 on 2026-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_property_source_type_sinyidetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinyidetail',
            name='add_layout',
            field=models.TextField(blank=True, null=True, verbose_name='addLayout'),
        ),
        migrations.AlterField(
            model_name='sinyidetail',
            name='image_tag',
            field=models.TextField(blank=True, null=True, verbose_name='imageTag'),
        ),
        migrations.AlterField(
            model_name='sinyidetail',
            name='parking',
            field=models.TextField(blank=True, null=True, verbose_name='parking'),
        ),
        migrations.AlterField(
            model_name='sinyidetail',
            name='total_layout',
            field=models.TextField(blank=True, null=True, verbose_name='totalLayout'),
        ),
    ]
