# Generated by Django 5.2.13 on 2026-06-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sinyidetail_add_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinyidetail',
            name='total_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='totalPrice'),
        ),
    ]
