# Generated by Django 5.2.13 on 2026-06-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_favoriteproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproperty',
            options={'verbose_name': '我的收藏'},
        ),
    ]
