# Generated by Django 5.2.13 on 2026-06-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_favoriteproperty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house591existingdetail',
            name='total_price',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='總價'),
        ),
        migrations.AlterField(
            model_name='house591existingdetail',
            name='views',
            field=models.IntegerField(db_index=True, default=0, verbose_name='瀏覽次數'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_presale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_presale'),
        ),
        migrations.AddIndex(
            model_name='sinyidetail',
            index=models.Index(fields=['total_price'], name='sinyi_detai_total_p_11ba82_idx'),
        ),
    ]
